#!/bin/sh

# function used to clean only the CFD directory of this simulation
# used for intermediary testing of CFD sub-model

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove foam visualization objects
rm -f *.foam

# remove processor folders for parallel run
rm -rf processor*

# remove logs
rm log.* > /dev/null 2>&1

# cleanCase, savining initial time conditions (0.01)
mv 0 orig_0
cleanTimeDirectories
mv orig_0 0

#------------------------------------------------------------------------------
