#!/bin/sh

# function used to clean only the CFD mesh
# used for intermediary testing of CFD mesh and sub-model

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove surface and features
#rm -f constant/triSurface/motorBike.obj.gz > /dev/null 2>&1
rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f constant/triSurface/*.eMesh > /dev/null 2>&1
rm -f constant/polyMesh > /dev/null 2>&1
rm -f *.foam

# remove processor folders for parallel run
rm -rf processor* > /dev/null 2>&1

# remove initial conditions folder
# rm -rf 0 > /dev/null 2>&1

# remove logs
rm log.* > /dev/null 2>&1

mv 0 orig_0
cleanCase
mv orig_0 0

#------------------------------------------------------------------------------
